<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
    <head>
        <base href="<!--root-->" />
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
        <link rel='stylesheet' href='/css/reset,default4,dde,mce' type='text/css' />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="keywords" content="Brian Lai, Waterloo, KGV" />
        <meta name="description" content="Ohai: Brian Lai from the University of Waterloo." />
        <title><!--self.title--> | ohai.ca</title>
        <!--base href="http://ohai.ca" /-->
        <link rel="alternate" type="application/rss+xml" title="RSS" href="http://ohai.ca/rss">
        <!--self.headers-->
        <!--self.userheaders-->
    </head>

    <body>
        <div id="container">
            <div id="header">
                <div id="logo">
                    <a href="/">
                        <img src="/styles/logo100s.png" alt="" />
                    </a>
                </div>
                <div id="headermore">
                    <div class="col4">
                        <ul>
                            <li><a href="about/">About me</a></li>
                            <li><b>Brian Lai</b><br />
                                brian.lai@uwaterloo.ca<br />
                                tel: 519-888-4567</li>
                            <li><a href="http://ca.linkedin.com/in/goodtogo">LinkedIn</a></li>
                            <li><a href="http://facebook.com/fristpsot">Facebook</a></li>
                            <li><a href="http://twitter.com/type_boy">Twitter</a></li>
                        </ul>
                    </div>
                    <div class="col4">
                        <ul>
                            <li><a href="/goodies">Freeware</a></li>
                            <li><a href="http://github.com/1337">Github</a></li>
                            <li><a href="http://download.cnet.com/windows/thinc/3260-20_4-6280037.html">CNET profile</a></li>
                            <li><a href="http://planet-source-code.com/vb/authors/ShowBio.asp?lngAuthorId=22110576871&lngWId=1">Planet Source Code</a></li>
                        </ul>
                    </div>
                    <div class="col4">
                        <ul>
                            <li><a href="/blog">Blog</a></li>
                            <li><a href="/archives">Archives</a></li>
                            <li><a href="/search">Search</a></li>
                        </ul>
                    </div>
                    <div class="col4">
                        <ul>
                            <li><a href="/login">Login</a></li>
                            <li><a href="/menu">My profile</a></li>
                            <li><a href="/logout">Logout</a></li>
                            <li><a href="/register">Register</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div id="main" role="main">
                <!--div id="sidebar">
                    #Sidebar
                </div-->
                <div id="maincontent">
                     <!--self.content-->
                </div>
            </div>
            <div id="footer">
            </div>
        </div> <!--! end of #container -->
        <script type="text/javascript">
            $('#header').mouseenter(function(){$(this).animate({'height':'210px'},{queue:false});}).mouseleave(function(){$(this).animate({'height':'70px'},{queue:false});});
            var sc_project=4446854;var sc_invisible=1;var sc_partition=55;var sc_click_stat=1;var sc_security="74785e80";
        </script>
        <script type="text/javascript" src="http://www.statcounter.com/counter/counter_xhtml.js"></script>
        <noscript>
            <style type="text/css">
                #header:hover { height: 210px; }
            </style>
        </noscript>
    </body>
</html>
